### ISSUE TITLE
Can't build Fanduino window

### ISSUE THREAD

**Issue by Phill360** [szarvas/fanduino#1]
Visual Studio is reporting an error. I have taken a screenshot of the errors

![error](https://cloud.githubusercontent.com/assets/12110849/21640728/3adcd42e-d2cb-11e6-87ab-9ebee589b280.PNG)

**Comment by szarvas** [comment]
As present in the repo, the FanduinoWindow project depends on the Fanduino project. In the `FanduinoWindow.csproj` file you will find a reference to `..\Fanduino\bin\Release\Fanduino.exe`. This executable must be available when building Fanduino.

Simply put, if you checked out the whole repo as is, you should first go into the Fanduino directory and build a release version of that project first. Then you can build the FanduinoWindow project.

**Comment by Phill360** [comment]
Thanks for the reply. 
I have build a release version of the Fanduino project but when trying to build Fanduino Window I get an issue with ClickOnce

ClickOnce does not support the request execution level 'requireAdministrator'.		

Any idea how to fix this issue? I did some searching but i havent had any luck
thanks

**Comment by szarvas** [comment]
Never heard about ClickOnce before. Taking a quick look at it though, it is perfectly possible that you just can't use it for programs that require administrator privileges.

Fanduino needs admin privileges in order to read the hardware temperature sensors.

Try not using this ClickOnce thingy, that's my best guess, sorry.

https://i.stack.imgur.com/2884i.png
